
[buildpack]
id = "org.cloudfoundry.dotnet-core-conf"
name = ".NET Core Conf Buildpack"
version = "0.0.1"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
